// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package conditi;

import conditi.USERS;

/************************************************************/
/**
 * 
 */
public class ADULTS extends USERS {
	/**
	 * 
	 */
	public float fine = 1.0;
}
