// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package conditi;

import conditi.ITEMS;

/************************************************************/
/**
 * 
 */
public class BOOK extends ITEMS {
	/**
	 * 
	 */
	public String Language;
	/**
	 * 
	 */
	public String Publisher_name;
	/**
	 * 
	 */
	public int no_of_authors;
	/**
	 * 
	 */
	public String[] authors_name;
}
