// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package conditi;

import conditi.ITEMS;

/************************************************************/
/**
 * 
 */
public class CD extends ITEMS {
	/**
	 * 
	 */
	public String Producer_name;
	/**
	 * 
	 */
	public int no_of_artists;
	/**
	 * 
	 */
	public String[] artists;
}
