// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package conditi;

import conditi.USERS;

/************************************************************/
/**
 * 
 */
public class CHILDREN extends USERS {
	/**
	 * 
	 */
	public float fine = 0.05;
}
