// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package conditi;

/************************************************************/
/**
 * 
 */
public class CLERK {
	/**
	 * 
	 */
	public float fine_collected;
	/**
	 * 
	 */
	public boolean damaged;

	/**
	 * 
	 */
	public void check_damage() {
	}

	/**
	 * 
	 * @param due_date 
	 * @param date_of_return 
	 */
	public void calculate_fine(String due_date, String date_of_return) {
	}

	/**
	 * 
	 * @param user_id 
	 * @param collection_no 
	 * @param date_of_borrow 
	 */
	public void update1(int user_id, int collection_no, String date_of_borrow) {
	}

	/**
	 * 
	 * @param date_of_return 
	 * @param fine 
	 */
	public void update2(String date_of_return, float fine) {
	}
}
