// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package conditi;

/************************************************************/
/**
 * 
 */
public class DCL {
	/**
	 * 
	 */
	public int no_of_libraries;
	/**
	 * 
	 */
	public String last_updated_date;

	/**
	 * 
	 * @param collection_no 
	 */
	public void update(int collection_no) {
	}

	/**
	 * 
	 */
	public void order() {
	}

	/**
	 * 
	 * @param collection_no 
	 */
	public void remove(int collection_no) {
	}
}
