// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package conditi;

/************************************************************/
/**
 * 
 */
public class LIBRARY {
	/**
	 * 
	 */
	public String name;
	/**
	 * 
	 */
	public String address;
	/**
	 * 
	 */
	public int id;
}
