// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package conditi;

import conditi.USERS;

/************************************************************/
/**
 * 
 */
public class SENIOR extends USERS {
	/**
	 * 
	 */
	public float fine = 0.5;
}
