// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package conditi;

/************************************************************/
/**
 * 
 */
public class USERS {
	/**
	 * 
	 */
	public String user_id;
	/**
	 * 
	 */
	public String address;
	/**
	 * 
	 */
	public String phone_no;
	/**
	 * 
	 */
	public int date_of_return;
	/**
	 * 
	 */
	public String date_of_borrow;
	/**
	 * 
	 */
	public String duedate;

	/**
	 * 
	 * @param collection_no 
	 */
	public void borrows(int collection_no) {
	}

	/**
	 * 
	 * @param collection_no 
	 */
	public void returns(int collection_no) {
	}
}
