// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project_domainModel;

/************************************************************/
/**
 * 
 */
public class Admin {
	/**
	 * 
	 */
	private int admin_id;
	/**
	 * 
	 */
	private int rev_id;
	/**
	 * 
	 */
	private int res_id;
	/**
	 * 
	 */
	private int order_id;
	/**
	 * 
	 */
	private int rider_id;
	/**
	 * 
	 */
	private int bill_id;
}
