// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project_domainModel;

/************************************************************/
/**
 * 
 */
public class Billing {
	/**
	 * 
	 */
	private int Bill_id;
	/**
	 * 
	 */
	private int cus_id;
	/**
	 * 
	 */
	private int Order_id;
	/**
	 * 
	 */
	private int rider_id;
	/**
	 * 
	 */
	private String payment_method;
	/**
	 * 
	 */
	private String address;
	/**
	 * 
	 */
	private String Postal_code;
}
