// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project_domainModel;

/************************************************************/
/**
 * 
 */
public class Card_info {
	/**
	 * 
	 */
	private String Card_no;
	/**
	 * 
	 */
	private int cus_id;
	/**
	 * 
	 */
	private String Card_expire;
	/**
	 * 
	 */
	private String cvc;
	/**
	 * 
	 */
	private String Card_holder_name;
}
