// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project_domainModel;

/************************************************************/
/**
 * 
 */
public class Category {
	/**
	 * 
	 */
	private int Category_id;
	/**
	 * 
	 */
	private String category_name;
	/**
	 * 
	 */
	private String toppings;
	/**
	 * 
	 */
	private float topping_price;
	/**
	 * 
	 */
	private String image_url;
}
