// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project_domainModel;

/************************************************************/
/**
 * 
 */
public class Customer {
	/**
	 * 
	 */
	private int cus_id;
	/**
	 * 
	 */
	private String cus_name;
	/**
	 * 
	 */
	private String cus_phone;
	/**
	 * 
	 */
	private String cus_email;
	/**
	 * 
	 */
	private String cus_pass;
	/**
	 * 
	 */
	private boolean Premium;
}
