// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project_domainModel;

/************************************************************/
/**
 * 
 */
public class Food
Ordering System
{
	/**
	 * 
	 */
	private String Admin_name;
	/**
	 * 
	 */
	private String Admin_password;
	/**
	 * 
	 */
	private int No_of_restaurants;
	/**
	 * 
	 */
	private int No_of_riders;
}
