// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project_domainModel;

/************************************************************/
/**
 * 
 */
public class Food {
	/**
	 * 
	 */
	private int food_id;
	/**
	 * 
	 */
	private String food_name;
	/**
	 * 
	 */
	private float food_price;
	/**
	 * 
	 */
	private int Category_id;
	/**
	 * 
	 */
	private int res_id;
	/**
	 * 
	 */
	private String image_url;
}
