// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project_domainModel;

/************************************************************/
/**
 * 
 */
public class Order {
	/**
	 * 
	 */
	private int order_id;
	/**
	 * 
	 */
	private int cus_id;
	/**
	 * 
	 */
	private int rider_id;
	/**
	 * 
	 */
	private String order_date;
	/**
	 * 
	 */
	private int discount;
	/**
	 * 
	 */
	private float total_price;
	/**
	 * 
	 */
	private float discounted_price;
	/**
	 * 
	 */
	private boolean checkout;
}
