// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project_domainModel;

/************************************************************/
/**
 * 
 */
public class Restaurant {
	/**
	 * 
	 */
	private int restaurant_id;
	/**
	 * 
	 */
	private String restaurant_name;
	/**
	 * 
	 */
	private int category_id;
	/**
	 * 
	 */
	private String url_image;
}
