// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project_domainModel;

/************************************************************/
/**
 * 
 */
public class Reviews {
	/**
	 * 
	 */
	private int rev_id;
	/**
	 * 
	 */
	private int cus_id;
	/**
	 * 
	 */
	private int order_id;
	/**
	 * 
	 */
	private String review;
	/**
	 * 
	 */
	private String review_date;
}
