// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project_domainModel;

/************************************************************/
/**
 * 
 */
public class Rider {
	/**
	 * 
	 */
	private int rider_id;
	/**
	 * 
	 */
	private String rider_name;
	/**
	 * 
	 */
	private String rider_phone;
	/**
	 * 
	 */
	private String vehicle_num_plate;
	/**
	 * 
	 */
	private String rider_cnic;
}
