// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project_domainModel;

/************************************************************/
/**
 * 
 */
public class Suborder extends Order {
	/**
	 * 
	 */
	private int sub_order_id;
	/**
	 * 
	 */
	private int order_id;
	/**
	 * 
	 */
	private int res_id;
	/**
	 * 
	 */
	private int category_id;
	/**
	 * 
	 */
	private int food_id;
	/**
	 * 
	 */
	private float food_price;
}
