// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package sdaAssignment2;

/************************************************************/
/**
 * 
 */
public class DCL {
	/**
	 * 
	 */
	public int no_of_libraries;
	/**
	 * 
	 */
	public String last_updated_date;
	/**
	 * 
	 */
	private int library_Count;
	/**
	 * 
	 */
	private String previous_updated_date;

	/**
	 * 
	 * @param collection_no 
	 */
	public void update(int collection_no) {
	}

	/**
	 * 
	 */
	public void order() {
	}

	/**
	 * 
	 * @param collection_no 
	 */
	public void remove(int collection_no) {
	}

	/**
	 * 
	 * @param collection_number 
	 */
	public void Update_Datbase(int collection_number) {
	}

	/**
	 * 
	 */
	public void OrdernewBooks() {
	}

	/**
	 * 
	 * @param collection_number 
	 */
	public void removeBooks(int collection_number) {
	}

	/**
	 * 
	 */
	public void Catalogues_Supplier_items() {
	}
}
