// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package sdaAssignment2;

/************************************************************/
/**
 * 
 */
public class SENIOR extends USERS {
	/**
	 * 
	 */
	public float fine = 0.5;
	/**
	 * 
	 */
	public float FineAmount = 1.0;
}
