// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package sdaAssignment2;

/************************************************************/
/**
 * 
 */
public class USERS {
	/**
	 * 
	 */
	public String user_id;
	/**
	 * 
	 */
	public String address;
	/**
	 * 
	 */
	public String phone_no;
	/**
	 * 
	 */
	public int date_of_return;
	/**
	 * 
	 */
	public String date_of_borrow;
	/**
	 * 
	 */
	public String duedate;
	/**
	 * 
	 */
	private String user_id;
	/**
	 * 
	 */
	private String DateIssued;
	/**
	 * 
	 */
	private String address;
	/**
	 * 
	 */
	private String PhoneNumber;
	/**
	 * 
	 */
	public String DateReturned;
	/**
	 * 
	 */
	private int DueDate;

	/**
	 * 
	 * @param collection_no 
	 */
	public void borrows(int collection_no) {
	}

	/**
	 * 
	 * @param collection_no 
	 */
	public void returns(int collection_no) {
	}

	/**
	 * 
	 * @param collection_no 
	 */
	public void BorrowBooks(int collection_no) {
	}

	/**
	 * 
	 * @param collection_no 
	 */
	public void ReturnsBook(int collection_no) {
	}
}
