// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package sdaAssignment2;

/************************************************************/
/**
 * 
 */
public class WholeSaler {
	/**
	 * 
	 */
	public int supplier_id;
	/**
	 * 
	 */
	public String supplier_name;
	/**
	 * 
	 */
	private int Supplier_identity_no;

	/**
	 * 
	 */
	public void supply_items() {
	}
}
