// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package OrderManagment-SequenceDiagram;

/************************************************************/
/**
 * 
 */
public class OrderManagement {
}
