// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Delivery_management_collaboration;

/************************************************************/
/**
 * 
 */
public class Delivery_Management {
}
