// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BillingManagement-SequenceDiagram;

/************************************************************/
/**
 * 
 */
public class BillingManagement-SequenceDiagram {
}
