// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package FoodManagement-ActivityDiagram;

/************************************************************/
/**
 * 
 */
public class OrderManagement {
}
