// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DeliveryManagement-SequenceDiagram;

/************************************************************/
/**
 * 
 */
public class DeliveryManagement {
}
