// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package FoodOrdering-DeploymentDiagram.Deployment.Container;

/************************************************************/
/**
 * 
 */
public class Customer {
}
