// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package conditi;

/************************************************************/
/**
 * 
 */
public class ITEMS {
	/**
	 * 
	 */
	public int collection_no;
	/**
	 * 
	 */
	public String title;
	/**
	 * 
	 */
	public String ISBN;
	/**
	 * 
	 */
	public String condition;
	/**
	 * 
	 */
	public boolean borrowed_this_yr;
}
