-- Task 01

SELECT DEPARTMENT_ID, COUNT(*) AS "NO OF EMPLOYEES", ROUND(AVG(SALARY)) FROM EMPLOYEES 
GROUP BY DEPARTMENT_ID;

-- Task 02
SELECT JOB_ID, COUNT(*) FROM EMPLOYEES 
GROUP BY JOB_ID;

-- Task 03

SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES
WHERE HIRE_DATE > 
(SELECT HIRE_DATE FROM EMPLOYEES WHERE EMPLOYEE_ID=110);

-- Task 04

SELECT DEPARTMENT_ID, MAX(SALARY) AS "HIGHEST SALARY IN DEPT" 
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING MAX(SALARY)>1500 ORDER BY DEPARTMENT_ID asc;

-- Task 05

SELECT EMPLOYEE_ID AS "EMPLOYEE NUMBER", first_name||' '|| LAST_NAME
AS NAME, JOB_ID AS "JOB_TITLE", SALARY AS SALARY FROM EMPLOYEES WHERE SALARY < 
ANY (SELECT SALARY FROM EMPLOYEES WHERE JOB_ID='IT_PROG');

SELECT MIN(SALARY) FROM EMPLOYEES WHERE JOB_ID='IT_PROG';
-- Task 06

SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID 
NOT IN ( SELECT EMPLOYEE_ID FROM JOB_HISTORY);

-- Task 07

SELECT MANAGER_ID AS "MANAGER NUMBER", MIN(SALARY)  FROM EMPLOYEES 
GROUP BY MANAGER_ID ORDER BY MANAGER_ID ASC;

--TASK 8
CREATE TABLE EMPLOYEE_BKP AS SELECT * FROM EMPLOYEES WHERE 1=2;
SELECT * FROM DEPARTMENTS;
INSERT INTO EMPLOYEE_BKP SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM JOB_HISTORY WHERE START_DATE='13-JAN-01');

--TASK 9
UPDATE EMPLOYEES SET SALARY=SALARY+(0.2*SALARY) WHERE JOB_ID IN(SELECT JOB_ID FROM JOBS WHERE MIN_SALARY=6000);

--TASK 10
DELETE FROM EMPLOYEE_BKP 
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE MANAGER_ID IS NOT NULL AND DEPARTMENT_NAME='FINANCE');