// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project_usecase.Food

Ordering and Management System;

/************************************************************/
/**
 * 
 */
public class Display
Menu Categories
{
}
