// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package conditi;

/************************************************************/
/**
 * 
 */
public class SUPPLIER {
	/**
	 * 
	 */
	public int supplier_id;
	/**
	 * 
	 */
	public String supplier_name;

	/**
	 * 
	 */
	public void supply_items() {
	}
}
