// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package hospitalSystem;

/************************************************************/
/**
 * 
 */
public class Consultant Doctor extends Doctor
 {
				/**
				 * 
				 */
				public String Leading_Team;
				/**
				 * 
				 */
				public String LeadingTeam;
}
