// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package hospitalSystem;

/************************************************************/
/**
 * 
 */
public class Doctor {
	/**
	 * 
	 */
	public String[] Speciality;
	/**
	 * 
	 */
	public String[] Location;
	/**
	 * 
	 */
	public String Speciality;
	/**
	 * 
	 */
	public String Locations;
}
