// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package hospitalSystem;

/************************************************************/
/**
 * 
 */
public class Junior Doctor extends Doctor
 {
				/**
				 * 
				 */
				public String name;
				/**
				 * 
				 */
				public String Name;
}
