// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package hospitalSystem;

/************************************************************/
/**
 * 
 */
public class Ward {
	/**
	 * 
	 */
	public String name;
	/**
	 * 
	 */
	public String PatientGender;
	/**
	 * 
	 */
	public int Capacity;
	/**
	 * 
	 */
	public String Name;
	/**
	 * 
	 */
	public String PatientGender;
	/**
	 * 
	 */
	public int Capacity;
}
