// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project_collaborationDiagram;

/************************************************************/
/**
 * 
 */
public class Food Ordering system
{
	/**
	 * 
	 */
	public project_collaborationDiagram.Food Ordering system;
	/**
	 * 
	 */
	public project_collaborationDiagram.Food Ordering system;
	/**
	 * 
	 */
	public project_collaborationDiagram.Food Ordering system;
	/**
	 * 
	 */
	public project_collaborationDiagram.Food Ordering system;
}
