// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package hospitalSystem;

/************************************************************/
/**
 * 
 */
public class Hospital {
	/**
	 * 
	 */
	public String Name;
	/**
	 * 
	 */
	public String Address;
	/**
	 * 
	 */
	public String Name;
	/**
	 * 
	 */
	public String Address;
}
