// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package hospitalSystem;

/************************************************************/
/**
 * 
 */
public class Patient {
	/**
	 * 
	 */
	public String id;
	/**
	 * 
	 */
	public String gender;
	/**
	 * 
	 */
	public int age;
	/**
	 * 
	 */
	public EcorePrimitiveTypes.EDate accepted;
	/**
	 * 
	 */
	public String sickness;
	/**
	 * 
	 */
	public String[] prescriptions;
	/**
	 * 
	 */
	public String id;
	/**
	 * 
	 */
	public String Gender;
	/**
	 * 
	 */
	public int Age;
	/**
	 * 
	 */
	public String Accepted;
	/**
	 * 
	 */
	public String Sickness;
	/**
	 * 
	 */
	public String Prescription;
}
