// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package hospitalSystem;

/************************************************************/
/**
 * 
 */
public class Team {
	/**
	 * 
	 */
	public String name;
	/**
	 * 
	 */
	public int NumofEmployees;
	/**
	 * 
	 */
	public String Name;
	/**
	 * 
	 */
	public int NumberOfEmployees;
}
