// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package sdaAssignment2;

/************************************************************/
/**
 * 
 */
public class Books extends ITEMS {
	/**
	 * 
	 */
	public String Language;
	/**
	 * 
	 */
	public String PublisherName;
	/**
	 * 
	 */
	public String[] AuthorNames;
}
