// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package sdaAssignment2;

/************************************************************/
/**
 * 
 */
public class CD extends ITEMS {
	/**
	 * 
	 */
	public String Producer_name;
	/**
	 * 
	 */
	public int no_of_artists;
	/**
	 * 
	 */
	public String[] artists;
	/**
	 * 
	 */
	public String ProducerName;
	/**
	 * 
	 */
	public String[] ArtistNames;
}
