// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package sdaAssignment2;

/************************************************************/
/**
 * 
 */
public class CHILDREN extends USERS {
	/**
	 * 
	 */
	public float fine = 0.05;
	/**
	 * 
	 */
	public float FineAmount = 1.0;
}
