// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package sdaAssignment2;

/************************************************************/
/**
 * 
 */
public class ITEMS {
	/**
	 * 
	 */
	public int collection_no;
	/**
	 * 
	 */
	public String title;
	/**
	 * 
	 */
	public String ISBN;
	/**
	 * 
	 */
	public String condition;
	/**
	 * 
	 */
	public boolean borrowed_this_yr;
	/**
	 * 
	 */
	private int collectionNumber;
	/**
	 * 
	 */
	private String Title;
	/**
	 * 
	 */
	private String ISBN;
	/**
	 * 
	 */
	private boolean DamageCondition;
}
