// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package sdaAssignment2;

/************************************************************/
/**
 * 
 */
public class LIBRARY {
	/**
	 * 
	 */
	public String name;
	/**
	 * 
	 */
	public String address;
	/**
	 * 
	 */
	public int id;
	/**
	 * 
	 */
	private int Library_Id;
}
