// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ComponentDiagram;

/************************************************************/
/**
 * 
 */
public class Accounts {
	/**
	 * 
	 */
	public interface  {
	};
	/**
	 * 
	 */
	public interface  {
	};
				/**
				 * 
				 */
				public undef Port3;
				/**
				 * 
				 */
				public undef Port6;
}
