// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ComponentDiagram;

/************************************************************/
/**
 * 
 */
public class Database {
	/**
	 * 
	 */
	public interface  {
	};
				/**
				 * 
				 */
				public undef Port1;
}
