// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ComponentDiagram;

/************************************************************/
/**
 * 
 */
public class System {
	/**
	 * 
	 */
	public interface
	{
	};

	/**
	 * 
	 */
	public interface Select
	restaurant from categories
	{
		};
		/**
		 * 
		 */
		public interface
		{
		};

		/**
		 * 
		 */
		public interface Order
		items from restaurant
		{
			};
			/**
			 * 
			 */
			public interface
			{
			};
			/**
			 * 
			 */
			public interface
			{
			};
			/**
			 * 
			 */
			public undef Port8;
			/**
			 * 
			 */
			public undef Port9;
}
